import type { Personnel, WeekSchedule } from "./types";

export const PERSONNEL: Personnel[] = [
  {
    id: "P001",
    name: "Ahmet Yılmaz",
    employee_id: "100001",
    phone: "+90 532 111 22 33",
    email: "ahmet.yilmaz@izmir-merkez.com",
    hire_date: "2022-03-15",
    contract_end_date: "",
    title: "Kasiyer",
    employment_type: "full_time",
    status: "active",
    erp_id: "SAP-00001",
    notes: "",
    skills: ["Kasa", "Reyon"],
    skill_levels: { Kasa: "primary", Reyon: "secondary" },
    availability: { 0: "available", 1: "available", 2: "preferred_not", 3: "available", 4: "available", 5: "preferred_not", 6: "unavailable" },
    preferred_shift: "morning",
    max_weekly_hours: 45,
    overtime_approved: false,
    prev_score: 32,
    hero_count: 1,
    no_show_count: 0,
    late_count: 2,
    annual_leave_days_total: 14,
    leave_records: [
      { id: "L001", type: "annual", start_date: "2026-04-01", end_date: "2026-04-07", days: 5, note: "" },
    ],
  },
  {
    id: "P002",
    name: "Fatma Şahin",
    employee_id: "100002",
    phone: "+90 543 222 33 44",
    email: "fatma.sahin@izmir-merkez.com",
    hire_date: "2021-07-01",
    contract_end_date: "",
    title: "Kasa Sorumlusu",
    employment_type: "full_time",
    status: "active",
    erp_id: "SAP-00002",
    notes: "Cumartesi sabah tercih ediyor.",
    skills: ["Kasa", "Mutfak"],
    skill_levels: { Kasa: "primary", Mutfak: "secondary" },
    availability: { 0: "available", 1: "unavailable", 2: "available", 3: "available", 4: "preferred_not", 5: "available", 6: "available" },
    preferred_shift: "any",
    max_weekly_hours: 45,
    overtime_approved: true,
    prev_score: 28,
    hero_count: 3,
    no_show_count: 0,
    late_count: 0,
    annual_leave_days_total: 20,
    leave_records: [
      { id: "L002", type: "annual", start_date: "2026-02-16", end_date: "2026-02-21", days: 5, note: "Aile ziyareti" },
      { id: "L003", type: "annual", start_date: "2026-03-24", end_date: "2026-03-28", days: 3, note: "" },
    ],
  },
  {
    id: "P003",
    name: "Mehmet Demir",
    employee_id: "100003",
    phone: "+90 505 333 44 55",
    email: "mehmet.demir@izmir-merkez.com",
    hire_date: "2023-01-10",
    contract_end_date: "2026-12-31",
    title: "Teras Görevlisi",
    employment_type: "part_time",
    status: "active",
    erp_id: "SAP-00003",
    notes: "Part-time — haftada max 30 saat.",
    skills: ["Teras", "Reyon"],
    skill_levels: { Teras: "primary", Reyon: "secondary" },
    availability: { 0: "preferred_not", 1: "available", 2: "available", 3: "unavailable", 4: "available", 5: "available", 6: "preferred_not" },
    preferred_shift: "evening",
    max_weekly_hours: 30,
    overtime_approved: false,
    prev_score: 35,
    hero_count: 0,
    no_show_count: 1,
    late_count: 3,
    annual_leave_days_total: 14,
    leave_records: [
      { id: "L004", type: "excuse", start_date: "2026-01-13", end_date: "2026-01-14", days: 2, note: "Randevu" },
    ],
  },
  {
    id: "P004",
    name: "Ayşe Kaya",
    employee_id: "100004",
    phone: "+90 532 444 55 66",
    email: "ayse.kaya@izmir-merkez.com",
    hire_date: "2020-09-20",
    contract_end_date: "",
    title: "Kıdemli Kasiyer",
    employment_type: "full_time",
    status: "active",
    erp_id: "SAP-00004",
    notes: "",
    skills: ["Kasa", "Teras"],
    skill_levels: { Kasa: "primary", Teras: "primary" },
    availability: { 0: "available", 1: "available", 2: "unavailable", 3: "available", 4: "available", 5: "unavailable", 6: "available" },
    preferred_shift: "morning",
    max_weekly_hours: 45,
    overtime_approved: true,
    prev_score: 30,
    hero_count: 2,
    no_show_count: 0,
    late_count: 1,
    annual_leave_days_total: 20,
    leave_records: [
      { id: "L005", type: "annual", start_date: "2026-01-19", end_date: "2026-01-30", days: 10, note: "Yıl sonu" },
      { id: "L006", type: "sick",   start_date: "2026-03-03", end_date: "2026-03-04", days: 2,  note: "Doktor raporu" },
    ],
  },
  {
    id: "P005",
    name: "Ali Çelik",
    employee_id: "100005",
    phone: "+90 543 555 66 77",
    email: "ali.celik@izmir-merkez.com",
    hire_date: "2024-02-01",
    contract_end_date: "",
    title: "Mutfak Görevlisi",
    employment_type: "full_time",
    status: "on_leave",
    erp_id: "SAP-00005",
    notes: "28 Mayıs–5 Haziran arası yıllık izin.",
    skills: ["Mutfak", "Reyon"],
    skill_levels: { Mutfak: "primary", Reyon: "secondary" },
    availability: { 0: "unavailable", 1: "available", 2: "available", 3: "available", 4: "preferred_not", 5: "available", 6: "available" },
    preferred_shift: "any",
    max_weekly_hours: 45,
    overtime_approved: false,
    prev_score: 25,
    hero_count: 0,
    no_show_count: 2,
    late_count: 4,
    annual_leave_days_total: 14,
    leave_records: [
      { id: "L007", type: "annual", start_date: "2026-03-09", end_date: "2026-03-21", days: 10, note: "" },
      { id: "L008", type: "annual", start_date: "2026-05-26", end_date: "2026-06-04", days: 7,  note: "Onaylı — yönetici notu" },
    ],
  },
  {
    id: "P006",
    name: "Zeynep Arslan",
    employee_id: "100006",
    phone: "+90 505 666 77 88",
    email: "zeynep.arslan@izmir-merkez.com",
    hire_date: "2019-11-05",
    contract_end_date: "",
    title: "Mağaza Şefi",
    employment_type: "full_time",
    status: "active",
    erp_id: "SAP-00006",
    notes: "Kıdemli çalışan. Tüm alanlarda yetkin.",
    skills: ["Kasa", "Mutfak", "Teras"],
    skill_levels: { Kasa: "primary", Mutfak: "primary", Teras: "secondary" },
    availability: { 0: "available", 1: "preferred_not", 2: "available", 3: "available", 4: "available", 5: "available", 6: "unavailable" },
    preferred_shift: "any",
    max_weekly_hours: 45,
    overtime_approved: true,
    prev_score: 40,
    hero_count: 5,
    no_show_count: 0,
    late_count: 0,
    annual_leave_days_total: 26,
    leave_records: [
      { id: "L009", type: "annual", start_date: "2026-02-02", end_date: "2026-02-13", days: 10, note: "Yurt dışı" },
    ],
  },
];

export const MOCK_SCHEDULE: WeekSchedule = {
  fairnessGap: 0,
  scores: { P001: 56, P002: 56, P003: 56, P004: 56, P005: 56, P006: 56 },
  assignments: [
    { personnelId: "P001", day: 0, shiftId: 0, points: 3  },
    { personnelId: "P001", day: 1, shiftId: 1, points: 5  },
    { personnelId: "P001", day: 4, shiftId: 1, points: 8  },
    { personnelId: "P001", day: 5, shiftId: 1, points: 8  },
    { personnelId: "P002", day: 2, shiftId: 1, points: 5  },
    { personnelId: "P002", day: 3, shiftId: 1, points: 5  },
    { personnelId: "P002", day: 5, shiftId: 1, points: 8  },
    { personnelId: "P002", day: 6, shiftId: 1, points: 10 },
    { personnelId: "P003", day: 1, shiftId: 1, points: 5  },
    { personnelId: "P003", day: 4, shiftId: 0, points: 8  },
    { personnelId: "P003", day: 5, shiftId: 0, points: 8  },
    { personnelId: "P004", day: 1, shiftId: 0, points: 3  },
    { personnelId: "P004", day: 3, shiftId: 1, points: 5  },
    { personnelId: "P004", day: 4, shiftId: 1, points: 8  },
    { personnelId: "P004", day: 6, shiftId: 1, points: 10 },
    { personnelId: "P005", day: 1, shiftId: 0, points: 3  },
    { personnelId: "P005", day: 2, shiftId: 1, points: 5  },
    { personnelId: "P005", day: 3, shiftId: 1, points: 5  },
    { personnelId: "P005", day: 5, shiftId: 0, points: 8  },
    { personnelId: "P005", day: 6, shiftId: 1, points: 10 },
    { personnelId: "P006", day: 0, shiftId: 0, points: 3  },
    { personnelId: "P006", day: 2, shiftId: 1, points: 5  },
    { personnelId: "P006", day: 4, shiftId: 1, points: 8  },
  ],
};
