/** Sahne 2 (telefon): ekip üyesi: bildirim → gelecek haftanın vardiyaları → vardiyaya dokununca seçenekler. Plan yayınlıyken çekilir */
import { open, go, login, startRec, encode, cursorStart, click, hover, focus, reset, wait, caption } from "./rec.mjs";
const D = process.env.FRAMES || "/tmp/vid_s2";
const { b, page } = await open({ mobile: true });
await login(page, "v.burak.tan", "vitrin123", "/portal/login");
await go(page, "/portal");
await wait(page, 200);
const rec = await startRec(page, D);
await cursorStart(page, 195, 500);
await caption(page, "Plan yayınlanınca telefona bildirim gelir", 1);
await wait(page, 1200);
await click(page, page.locator('a[aria-label="Bildirimler"]:visible').first());
await page.waitForLoadState("networkidle");
await wait(page, 400);
await focus(page, { x: 195, y: (await page.getByText("Vardiya Programı Yayınlandı").first().boundingBox()).y + 30 }, 1.3);
await wait(page, 1400);
await reset(page);
await caption(page, "Vardiyalarını ve kiminle çalışacağını görür", 2);
await click(page, page.locator("nav a:visible", { hasText: "Vardiyalarım" }).last());
await page.waitForLoadState("networkidle");
await click(page, page.getByRole("button", { name: "Sonraki hafta" }));
await page.waitForLoadState("networkidle");
await wait(page, 500);
await focus(page, { x: 195, y: (await page.getByText(/Seninle:/).first().boundingBox()).y + 40 }, 1.3);
await wait(page, 1500);
await reset(page);
await caption(page, "Gelemiyorsa tek dokunuşla haber verir", 3);
await click(page, page.getByText(/Seninle:/).nth(1));
await wait(page, 1800);
await caption(page, "");
await wait(page, 500);
console.log(await rec.stop());
encode(D, "scripts/vid/out/phone.mp4", { width: 780, captions: rec.captions() });
await b.close();
