/** Sahne 2: ekip üyesi telefonda: bildirim → gelecek haftanın vardiyaları → vardiyaya dokununca seçenekler. Sahne 1'den sonra çekilir (plan yayınlı) */
import { open, go, login, startRec, encode, cursorStart, click, zoomTo, zoomOut, wait } from "./rec.mjs";
const D = process.env.FRAMES || "/tmp/vid_s2";
const { b, page } = await open({ mobile: true });
await login(page, "v.zeynep.kilic", "vitrin123", "/portal/login");
await go(page, "/portal");
await wait(page, 300);
const rec = await startRec(page, D);
await cursorStart(page, 200, 500);
await wait(page, 900);
await click(page, page.locator('a[aria-label="Bildirimler"]:visible').first(), 600);
await page.waitForLoadState("networkidle");
await wait(page, 700);
await zoomTo(page, page.getByText("Vardiya Programı Yayınlandı").first(), 1.25, 800, { centerX: true });
await wait(page, 1100);
await zoomOut(page, 700);
await click(page, page.locator("nav a:visible", { hasText: "Vardiyalarım" }).last(), 600);
await page.waitForLoadState("networkidle");
await wait(page, 600);
await click(page, page.getByRole("button", { name: "Sonraki hafta" }), 600);
await page.waitForLoadState("networkidle");
await wait(page, 900);
await zoomTo(page, page.getByText(/Seninle:/).first(), 1.25, 800, { centerX: true });
await wait(page, 1000);
await zoomOut(page, 700);
await click(page, page.getByText(/Seninle:/).nth(1), 600);
await wait(page, 1500);
console.log(await rec.stop());
encode(D, "scripts/vid/out/phone.mp4", { width: 780, crf: 26 });
await b.close();
