/** Sahne 4: yayınlı planda biri gelemiyor → önerilen yedekler gerekçeleriyle → Ata. Sahne 1'den sonra çekilir */
import { open, go, login, startRec, encode, cursorStart, click, hover, clickAt, cellOf, zoomTo, zoomOut, wait } from "./rec.mjs";
const D = process.env.FRAMES || "/tmp/vid_s4";
const WHO = process.env.WHO || "Pelin Acar", DAY = process.env.DAY || "Çar";
const { b, page } = await open();
await login(page, "vitrin.sorumlu", "vitrin123");
await go(page, "/schedule?week=next");
await wait(page, 300);
const cell = await cellOf(page, WHO, DAY);
const rec = await startRec(page, D);
await cursorStart(page, 1150, 760);
await wait(page, 500);
await zoomTo(page, cell, 1.6, 1000);
await wait(page, 300);
const z = await page.evaluate(() => window.__dir.cam());
await clickAt(page, cell.x * z.s + z.tx, cell.y * z.s + z.ty, 700);
await wait(page, 300);
await zoomOut(page, 700);
await page.getByText("Önerilen yedekler").waitFor({ timeout: 30000 });
await wait(page, 500);
await zoomTo(page, page.getByText("Önerilen yedekler").first(), 1.45, 900);
await hover(page, page.getByText(/uygun olduğunu girmiş/).first(), 700);
await wait(page, 1300);
await zoomOut(page, 700);
await click(page, page.getByRole("button", { name: "Ata" }).first(), 700);
await wait(page, 500);
rec.pause();
await page.getByText("Önerilen yedekler").waitFor({ state: "detached", timeout: 90000 });
await page.waitForLoadState("networkidle");
rec.resume();
await wait(page, 400);
await zoomTo(page, cell, 1.6, 1000);
await wait(page, 1400);
await zoomOut(page, 900);
await wait(page, 500);
console.log(await rec.stop());
encode(D, "scripts/vid/out/cover.mp4", { width: 1920, crf: 27 });
await b.close();
